permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Chaotic Pendulum"
id : "85732814424"
description : "Create your own beautiful chaos."
thumb: "thumb.gif"
version: "0.0.1"

ml_url: "http://minutelabs.io"
ml_library: "http://labs.minutelabs.io/library"
ml_assets: "http://labs.minutelabs.io/assets"
library_path: "library-build"

show :
  branding: true
  details: true
  comments: true
