permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Chaotic Pendulum"
id : "85732814424"
description : "Create your own beautiful chaos."
thumb: "thumb.gif"
version: "0.0.2"

ml_url: "//minutelabs.io"
ml_library: "//labs.minutelabs.io/library"
ml_assets: "//labs.minutelabs.io/assets"
library_path: "library-build"

show :
  branding: true
  details: true
  comments: true
